name: CI
on:
  push:
    branches: [ master, tests ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: sudo apt update && sudo apt -y install build-essential cmake
      - name: Run the tests
        run: |
          chmod +x ./test.sh
          ./test.sh
